# Generated by Django 2.0.7 on 2018-07-25 15:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]{11}\\Z'), '手机号应该为11位数字', 'invalid')], verbose_name='telephone'),
        ),
    ]
